# This Docker Compose file can be used to quickly bootup Dgraph Zero
# and Alpha in different Docker containers.

# It mounts /tmp/data on the host machine to /dgraph within the
# container. You will need to change /tmp/data to a more appropriate location.
# Run `docker-compose up` to start Dgraph.

services:
  zero:
    image: dgraph/dgraph:v24.0.0
    volumes:
      - ./dgraph-data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:v24.0.0
    volumes:
      - ./dgraph-data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0:255.255.255.255
  ratel:
    image: dgraph/ratel:v21.12.0
    ports:
      - 8000:8000

  server:
    build: .
    command: yarn start
    volumes:
      - .:/app
    environment:
      SERVER_PORT: 3000
      DB_HOST: alpha
      DB_PORT: 9080
    ports:
      - "3000:3000"
